### ISSUE TITLE
视频叠加的效果不正确

### ISSUE THREAD

**Issue by dourgulf** [lilingyu0620/LLYGPUImageDemo#1]
模拟器 iOS 13.7
Xcode 11.7 
直接运行出来是这个效果
![image](https://user-images.githubusercontent.com/1005591/96410329-508f8f00-1219-11eb-9d8c-05c71ef765dc.png)

**Comment by lilingyu0620** [comment]
用真机 GPUImage库有些效果不支持模拟器

**Comment by dourgulf** [comment]
并不是效果的问题，把滤镜去掉，就播放视频，出来的画面都是错的
